### ISSUE TITLE
Unable to use the value in .env in docker-compose 

### ISSUE THREAD

**Issue by kenchoong** [kenchoong/nestjs-cqrs#1]
When I use ${POSTGRES_USER} in docker-compose, the value cannot pass to the docker container. I will get the undefined, end up the `POSTGRES_DB` cannot initialize. 

```yml
environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
```

So right now need to hard code value in docker-compose yml as a temporary solution first
